import { useLocation } from 'react-router-dom';

export default function LegalPage() {
  const { pathname } = useLocation();
  const isPrivacy = pathname === '/privacy';

  return (
    <div className="max-w-2xl mx-auto py-8 space-y-8">
      <h1 className="text-3xl font-bold">{isPrivacy ? 'Privacy Policy' : 'Terms of Service'}</h1>
      <p className="text-sm text-gray-400">Last updated: June 2026</p>

      {isPrivacy ? (
        <div className="space-y-6 text-gray-700 leading-relaxed">
          <section className="space-y-2">
            <h2 className="text-lg font-bold text-gray-900">Information We Collect</h2>
            <p>PathHer AI collects information you provide during sign-up and onboarding, including your name, email address, education background, interests, strengths, career goals, and preferred work style. This data is used solely to personalise your career recommendations.</p>
          </section>
          <section className="space-y-2">
            <h2 className="text-lg font-bold text-gray-900">How We Use Your Data</h2>
            <p>Your profile data is sent to our AI service (Groq) to generate personalised career paths, course recommendations, and networking tips. We store the results in Firebase Firestore, secured to your account only.</p>
          </section>
          <section className="space-y-2">
            <h2 className="text-lg font-bold text-gray-900">Data Security</h2>
            <p>Your data is protected by Firebase Authentication and Firestore security rules that restrict access to your own account. We never sell your personal information to third parties.</p>
          </section>
          <section className="space-y-2">
            <h2 className="text-lg font-bold text-gray-900">Contact</h2>
            <p>For privacy enquiries, email us at <a href="mailto:support@pathher.app" className="text-purple-600 hover:underline">support@pathher.app</a>.</p>
          </section>
        </div>
      ) : (
        <div className="space-y-6 text-gray-700 leading-relaxed">
          <section className="space-y-2">
            <h2 className="text-lg font-bold text-gray-900">Acceptance</h2>
            <p>By using PathHer AI, you agree to these terms. PathHer AI is a career guidance platform designed for young women in South Africa.</p>
          </section>
          <section className="space-y-2">
            <h2 className="text-lg font-bold text-gray-900">Use of the Platform</h2>
            <p>You may use PathHer AI for personal, non-commercial career development purposes. You are responsible for maintaining the confidentiality of your account credentials.</p>
          </section>
          <section className="space-y-2">
            <h2 className="text-lg font-bold text-gray-900">AI-Generated Content</h2>
            <p>Career recommendations, courses, and insights are generated by AI and provided for guidance only. PathHer AI does not guarantee employment outcomes or the accuracy of third-party course URLs.</p>
          </section>
          <section className="space-y-2">
            <h2 className="text-lg font-bold text-gray-900">Contact</h2>
            <p>For questions about these terms, email <a href="mailto:support@pathher.app" className="text-purple-600 hover:underline">support@pathher.app</a>.</p>
          </section>
        </div>
      )}
    </div>
  );
}
